### PR TITLE
Change 'link href's to '//'

### PR DESCRIPTION
**Pull request by pitpalme**
Using '//' loads external resources using same protocol the page was
loaded with, i.e. 'https' when site is accessed securely and 'http' if
not.
No need to pin it to 'https' permanently, but it shouldn't be fixed
to 'http' either.

### CODE REVIEW

**Comment by christophmeissner** [comment]
Does not apply to external links, ie. not hosted by VP, or does it? When loading a page via https, it does not necessarily mean, the external resource is available via https as well...?

**Comment by Doca** [comment]
so merge or not merge?

**Comment by tordans** [comment]
Hi guys, my two cents: The `//` solution would work. But I don't see any reason not to just hard wire alle the change links to `httpS`. Google Fonts and the jQuery CDN will both work with https. And since you force visitor to https anyways, why not hard wire it in the code. We had edgecases with the // solution at betterplace.org and are happy since we moved to full https.

**Comment by pitpalme** [comment]
I wasn't aware of problems or edgecases and therefore intended to make the user just use the protocol used to call our site. As this is OSS others might not use HTTPS and my idea was to

- not downgrade (like it was for the font link)
- not *enforce* upgrade - although it's not a big deal, my personal preference was not to hardwire httpS

If votes for hardwiring secure protocol are major, I'll enhance PR by one more commit :)

**Pull request merged**
