### PR TITLE
Create Markdown enabled help type descriptions

### PR DESCRIPTION
**Pull request by pitpalme**
By introducing a new field to store "raw" description data and adding
markdown parser when saving description one can write "enriched"
descriptions, without the need to know HTML.
As markdown parser is configured to strip raw HTML in input, risk of
malicious javascript code in descriptions should be down to zero.

### CODE REVIEW

**Comment by pitpalme** [comment]
Review welcome!

Several times people asked me to emphasize something in help type description, so I decided to give some markdown support a shot, because I didn't want to allow plain HTML for several reasons ...

I might not have chosen the best way to deal with the problem, but at least it's something one can discuss about and improve/correct it :)

**Comment by maikhoepfel** [comment]
Wondering on a high level: is markdown really that user friendly to non-tech folks? Wouldn't a rich-text editor be friendlier? If I'm not mistaken, we only let people with admin access edit the texts, so I'm not as worried about allowing HTML.

**Comment by pitpalme** [comment]
Don't want people with half-baken HTML knowledge from ancient times to become creative and insert '<a href="javascript:foobar(); return false;">blaba</a>' ;)

Sure, RTE would be even friendlier. But I had no idea, how to get this done, while I got some rough idea, how to make use of markdown and how to describe to non-tech admin user(s).
The (here) relevant things are easy to remember (or write a cheat-sheet). And being enabled to have a [link](https://volunteer-planner.org) and write things **bold** would already cover a lot of requirements.

If there's an easy way to store "description" as result of a RTE I'm fine seeing PR closed and branch dropped ;)

**Comment by pitpalme** [comment]
OK, let me say "Thanks" for the broad hint. Let's pretend, this PR didn't exist, neither the branch ...

**Comment by maikhoepfel** [comment]
Sorry if I came across badly. I did not intend to dismiss your work at all, and adding markdown support would've still been an improvement. I just wondered aloud; no criticism intended. But I'm glad it worked out well now :)

**Comment by christophmeissner** [comment]
I'd prefer markdown as well. But I guess it can be hard to get into it without having worked with it before and little to no understanding of markup in general. Let's see, if we can have both options later.

**Comment by pitpalme** [comment]
@maikhoepfel never mind, you didn't. Ho harm done, sometimes one needs some criticism, to be lead to the right direction, especially if new to the whole infrastructure.

@christophmeissner I thought the same, but the more I think of it, the more I have to agree with the idea of using RTE for this specific type of text.
It's (perspectively) about to be edited by some kind of shift managing people that most probably have no technical skills. Additionally there should not be any need of "lists" or other markdown stuff not yet supported by RTE. It's only help type description area, that might use some simple text formatting (line break, strong, italic, ...) and maybe every now and than a link. That should be pretty much all of it.

I do, OTOH, see that markdown might nevertheless be useful for other areas, maybe like writing FAQs.

**Pull request closed without merging**
