### PR TITLE
Correct and extend installation notes for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by minthemiddle**
I corrected and extended the installation notes for Ubuntu 14.04. I mainly added small steps that may be obvious for experienced programmers, but may make a novice or inpatient one fail easily. Also, I added some directions of how to set up a superuser and manage the app via Django Admin.

### CODE REVIEW

**Comment by pitpalme** [comment]
Manually merged into branch `develop`.

**Comment by minthemiddle** [comment]
Splendid! I think we can avoid some manual work after we meet tonight and plan stuff together...

**Comment by XComp** [comment]
Hi guys,
I'd like to participate. Unfortunately, I'm busy today. Is such a meeting planned on a regular basis?

One thing that came to my mind is: Do you guys stay in touch with some people who actually use this tool? It would be good to get some feedback in order to know what needs to be improved.

Matthias

**Comment by Doca** [comment]
Hi Matthias, yes actually many of us volunteer in the camps also. The idea came up from the need to organize the volunteers form the local situation only ;-) The grew up locally so to say...

**Comment by XComp** [comment]
Cool, that's great. I also was at Rathaus Wilmersdorf once but was asked to register first. That's where I ran into the website for the first time.

It would be great if somebody could add a summary of today's meeting outcome to the wiki.

Thx, :)
Matthias

**Pull request closed without merging**
