### PR TITLE
Feature/dummydata factoryboy

### PR DESCRIPTION
**Pull request by Doca**
This commit creates dummy data with command "python manage.py create_dummy_data 5 --flush True"
If flush is added it's also deleting existing data in current tables (Needs,Topics, RegistrationProfile, User)
Admin users are not deleted.

### CODE REVIEW

**Comment by tordans** [comment]
@Doca I tried this out with a fresh install but got this error below.
It would be great to have a dummy data install. Any idea how to get it running?

```
$ python manage.py create_dummy_data 5 --flush True
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

**Comment by Doca** [comment]
Did you install the dependencies into your virtualenv like described in the readme file?

**Comment by maikhoepfel** [comment]
Tests are failing. Let me look into this.

**Comment by maikhoepfel** [comment]
Okay, I fixed the tests and rebased on develop. @Doca, the code changes look fine to me. Please merge at your convenience.

**Comment by maikhoepfel** [comment]
Just tried it out and it produced usable results for me. Merging, because I'm cowboy like that.

**Pull request merged**
