### PR TITLE
Refactor volunteer hour calculation

### PR DESCRIPTION
**Pull request by maikhoepfel**
We had two ways implemented to calculate the total number of volunteer
hours worked. One, a management command, required a cron job and relied
on the ValueStore model. The other used a SQL view, which needed manual
setting up.

I'd argue Django offers us everything we need to inexpensively calculate
the total number of hours. I've moved two existing template tags into
the new stats app, and reworked the one that calculates the total hours.

I've also added a default ordering to Needs.

### CODE REVIEW

**Comment by christophmeissner** [comment]
Am I missing a point here, or do we need to incorporate actually occupied slots which are over (ie. ending_time in filter instead starting_time) here, and multiply by slots_done, when slots_done is coming from Need.filter(endinging_time__lte=timezone.now()).annotate(slots_done=Count('registrationprofile'))?

**Comment by christophmeissner** [comment]
This would be sth. like 
    
    delta, now = timedelta(), datetime.now()
    for need in finished_needs:
        delta += need.slots_done * (now - need.starting_time)

**Comment by pitpalme** [comment]
To me calculation now looks correct. I've compared to MySQL view values and created test data in sqlite DB that has been worked on correctly too.

If someone wants to actually merge, I'm fine with it and happy to remove the view from DB, once this is going to be live.

**Comment by maikhoepfel** [comment]
Looking at it now, @pitpalme. Currently confused about why `slots_done` works.

**Comment by maikhoepfel** [comment]
@pitpalme could you or @christophmeissner do another review, and then merge as you see fit? Thanks.

**Comment by christophmeissner** [comment]
Nice!

**Pull request merged**
