### PR TITLE
Fix and improve registration/login/reset views

### PR DESCRIPTION
**Pull request by tordans**
- Extend the registration-base-template to include the same column
layout that was used on the registration page before.
- Refactor all related views to use this new block
„registration_content“.
- Minor styling changes to those views
- Add translation calls to all text strings inside those view
- Some minor changes to other views as well

## TODO for someone with a working dev environment
- [x] check if all views still render correctly
- [x] check if the color of form elements works inside the reset/registration/login views
- [x] check if the color of form elements still works in other places
- [x] check the translation strings - how do they work? Add the required changes to the translation file and such. Note: A few existing strings changed by being split up or small wording changes.
- [x] maybe change the strings inside those views from mixed DE or EN to one of the two

This addresses issue #97.

### CODE REVIEW

**Comment by tordans** [comment]
Hey guys, I hope someone can take over from there.

**Comment by Doca** [comment]
hey thanks a lot!

**Comment by pitpalme** [comment]
Thanks! :+1:

Will have a look at it and see if everything is working as expected.

**Comment by christophmeissner** [comment]
Hey! Thank you. You can create/update the translations file in 

`./manage.py makemessages --no-obsolete --no-wrap`

(the options are intended to make the output more git-friendly)

Compile the messages file with 

`./manage.py compilemessages`

Your local installation should be translated then. The .mo file created by `compilemessages` is gitignored, you'll need to (re-)generate it locally every time the .po file changes.

**Pull request merged**
